---
- name: Commvault Ansible
  gather_facts: no
  hosts: localhost
  connection: local

  vars:
    webconsole_hostname: 'hostname'
    commcell_username: 'username'
    commcell_password: 'password'
    client: 'sample client'

  tasks:
    - name: Commvault commcell initialization
      block:
        - name: Login
          commvault:
            operation: LOGIN
            entity: {
            webconsole_hostname: "{{ webconsole_hostname }}",
            commcell_username: "{{ commcell_username }}",
            commcell_password: "{{ commcell_password }}"
            }
          register: commcell
        - debug:
            msg: "Login is done successfully"
      rescue:
        - debug:
            msg: 'Login failed'

    - name: performing backup
      commvault:
        operation: "backup"
        entity_type: subclient
        commcell: "{{ commcell }}"
        entity: {
        client: "{{ client }}",
        agent: "file system",
        backupset: "defaultbackupset",
        subclient: "default"
        }
      register: backup_job

    - debug:
        msg: "Successfully started backup job: {{ backup_job.output }}"

...